### ISSUE TITLE
Missing Dependencies: SwiftyHTTP and SwiftyRanged

### ISSUE THREAD

**Issue by RayKitajima** [antonio-war/SwiftyGPT#1]
Hi Antonio, 

I noticed that the dependent libraries SwiftyHTTP and SwiftyRanged are missing from your repository. 
Was there a problem?

Thanks for your great work on this project!

**Comment by antonio-war** [comment]
Hey @RayKitajima, thanks for your report.
I'll fix this today in the new version 2.3.1, removing broken dependencies.

I'm also working on the new version 3.0.0, which will bring an update to the new OpenAI APIs and other features.
I hope to be able to complete it as soon as possible.

**Comment by RayKitajima** [comment]
Thanks for the excellent report. 
I'm excited to see the upcoming releases too!

**Comment by antonio-war** [comment]
I'm considering releasing version 3.0.0 directly, removing broken dependencies and updating APIs at least for the chat features.
Then I subsequently release new versions adding other features.

**Comment by RayKitajima** [comment]
I think it is a good decision.

I think the functionality of generative AI services will continue to grow, so middleware and abstraction layers like SwiftyGPT will be important in the Swift ecosystem, and I think a staged and stabled release that addresses this is important.

Let me know if there is anything the community can contribute for continuous upgrades.

Thanks!

**Comment by antonio-war** [comment]
If you want you can take a look to the develop branch, It's currently a work in progress, but it already gives an idea of what I want to do.
Unfortunately the documentation is not yet ready, but I hope the code is intuitive.

**Planned changes**
- Splitting the package in multiple modules, your application won't have to include the image stuffs, if your goal is to only use chat APIs.
- Remove dependencies and add some in the future only if **absolutely** necessary.
- The manager will be the main point of communication between your app and each module.
- Inside each manager you will be able to inject a service, which actually implements the manager's functionality.
- By default, the package will expose a NetworkingService which actually execute calls to the OpenAI API and a MockService which as you can imagine is a Mock service that can be used to test your application or inside SwiftUI preview.

It would be nice to hear your feedback on this!

**Comment by RayKitajima** [comment]
Thanks Antonio,

Unfortunately, I could not immediately incorporate the code from the develop branch and try it out, since my product uses only the SwiftyGPT image module.

But the new SwiftyGPT is well abstracted and I am looking forward SwiftyGPT to quickly incorporating non-OpenAI generative AI services!

**Comment by antonio-war** [comment]
Hey @RayKitajima, version 3.0.0 has been released!
I am closing the pull request as the failing dependencies are no longer present in the new version!

The image module you need, however, will be integrated into version 3.1.0. Which I will publish as soon as possible!
Thanks for your report, I hope you will appreciate the innovations introduced in SwiftyGPT.

**Comment by antonio-war** [comment]
Hey @RayKitajima, version 3.0.0 has been released!
I am closing the issue as the failing dependencies are no longer present in the new version!

The image module you need, however, will be integrated into version 3.1.0. 
Which I will publish as soon as possible!
Thanks for your report, I hope you will appreciate the innovations introduced in SwiftyGPT.
